### ISSUE TITLE
Support for motions and text objects

### ISSUE THREAD

**Issue by rkdals** [lutobler/vis-commentary#12]
Hi, thanks for your work on the plugin.

Although it's clearly outlined in the README that intended usage is for NORMAL and VISUAL modes, it'd be nice if vis-commentary could support motions and operator pending mode as does @tpope's original [vim-commentary](https://raw.githubusercontent.com/tpope/vim-commentary/master/doc/commentary.txt) (e.g. `gcip` to comment out a paragraph, `gc3k` to comment out 3 lines, etc.).

**Comment by lutobler** [comment]
I agree this would be a nice thing to add, but since I don't use Vis myself that much anymore, I'm not sure I want to do this myself. If you (or anyone) would add this, I would accept pull requests gladly.
